# Generated by Django 3.2.23 on 2023-12-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231214_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summary_detail',
        ),
    ]
