# Generated by Django 3.2.23 on 2023-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231214_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(to='api.Education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(to='api.Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.TextField(),
        ),
    ]
