# Generated by Django 3.2.23 on 2023-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231214_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='book_list', to='api.Skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
