# Generated by Django 3.2.23 on 2023-12-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20231215_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='authors',
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
