# Generated by Django 3.2.23 on 2023-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231215_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
