# Generated by Django 3.2.23 on 2023-12-15 09:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20231215_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(verbose_name=api.models.Education),
        ),
    ]
